cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'
tap 'caskroom/cask'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'
brew 'fzf'
brew 'n'
brew 'mongodb'
brew 'terraform'

cask '1password'
cask 'adium'
cask 'atom'
cask 'firefox'
cask 'garmin-express'
cask 'google-chrome'
cask 'handbrake'
cask 'mapbox-studio'
cask 'seashore'
cask 'slack'
cask 'steam'
cask 'tunnelbear'
cask 'vlc'
cask 'google-cloud-sdk'
